# Generated by Django 2.0.1 on 2018-01-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('parsed_id', models.CharField(max_length=255)),
                ('parsed_title', models.CharField(default='No Title', max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('playing', 'Playing'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='queued', max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
