# Generated by Django 2.0.1 on 2018-01-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='parsed_thumb',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
